# Generated by Django 2.2.6 on 2019-10-19 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miners_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_address', models.CharField(max_length=200, verbose_name='BTC Address')),
                ('btc_address_link', models.URLField(max_length=500, verbose_name='BTC Address Link')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('date_updated', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Date Updated')),
            ],
        ),
        migrations.AlterField(
            model_name='bronzepackage',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='BTC Amount to Mine'),
        ),
        migrations.AlterField(
            model_name='goldpackage',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='BTC Amount to Mine'),
        ),
        migrations.AlterField(
            model_name='platinumpackage',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='BTC Amount to Mine'),
        ),
        migrations.AlterField(
            model_name='silverpackage',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='BTC Amount to Mine'),
        ),
    ]
