# Generated by Django 2.2.6 on 2019-11-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miners_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bronzepackage',
            name='btc_address',
            field=models.CharField(max_length=500, verbose_name='BTC Address'),
        ),
        migrations.AlterField(
            model_name='goldpackage',
            name='btc_address',
            field=models.CharField(max_length=500, verbose_name='BTC Address'),
        ),
        migrations.AlterField(
            model_name='platinumpackage',
            name='btc_address',
            field=models.CharField(max_length=500, verbose_name='BTC Address'),
        ),
        migrations.AlterField(
            model_name='silverpackage',
            name='btc_address',
            field=models.CharField(max_length=500, verbose_name='BTC Address'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='btc_address',
            field=models.CharField(max_length=500, verbose_name='BTC Address'),
        ),
    ]
