# Generated by Django 2.2.6 on 2019-10-19 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miners_pages', '0002_auto_20191019_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bronzepackage',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='BTC Amount to Mine'),
        ),
        migrations.AlterField(
            model_name='goldpackage',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(15)], verbose_name='BTC Amount to Mine'),
        ),
        migrations.AlterField(
            model_name='platinumpackage',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(20)], verbose_name='BTC Amount to Mine'),
        ),
        migrations.AlterField(
            model_name='silverpackage',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(7)], verbose_name='BTC Amount to Mine'),
        ),
    ]
